title: acasema Blog
iconURL: assets/aks.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  github: acasemaSerrano

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 0
google_analytics: UA-NNNNNNNN-N
